I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 87, in script
    python:
  File "game/script.rpy", line 90, in <module>
    from firebase_fetcher import get_emotion
OSError: Cannot load native module 'Crypto.Hash._SHA256': Not found '_SHA256.cp312-mingw_x86_64_ucrt_llvm.pyd', Cannot load '_SHA256.pyd': Could not find module 'C:\Users\user\Downloads\renpy-8.4.1-sdk\lib\py3-windows-x86_64\lib\python3.12\site-packages\Crypto\Hash\_SHA256.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 87, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 90, in <module>
    from firebase_fetcher import get_emotion
  File "module/firebase_fetcher.py", line 2, in <module>
    import pyrebase
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/pyrebase/pyrebase.py", line 16, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/oauth2client/service_account.py", line 25, in <module>
    from oauth2client import client
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/oauth2client/client.py", line 45, in <module>
    from oauth2client import crypt
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/oauth2client/crypt.py", line 55, in <module>
    from oauth2client import _pycrypto_crypt
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/oauth2client/_pycrypto_crypt.py", line 16, in <module>
    from Crypto.Hash import SHA256
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/Crypto/Hash/SHA256.py", line 29, in <module>
    _raw_sha256_lib = load_pycryptodome_raw_lib("Crypto.Hash._SHA256",
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                            """
                            ^^^
    ...<15 lines>...
                                                size_t digest_size);
                                                ^^^^^^^^^^^^^^^^^^^^
                            """)
                            ^^^^
  File "lib/py3-windows-x86_64/lib/python3.12/site-packages/Crypto/Util/_raw_api.py", line 315, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._SHA256': Not found '_SHA256.cp312-mingw_x86_64_ucrt_llvm.pyd', Cannot load '_SHA256.pyd': Could not find module 'C:\Users\user\Downloads\renpy-8.4.1-sdk\lib\py3-windows-x86_64\lib\python3.12\site-packages\Crypto\Hash\_SHA256.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
SpeechPerfect 1.0
Wed Oct  8 01:52:59 2025
